name: auto_rickshaw_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.0
  country_picker: ^2.0.25
  flutter_otp_text_field: ^1.1.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/autos/
    - assets/images/booking/
    - assets/images/background/
    - assets/images/explore/

